name: Sign and Verify Artifact

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
      docker_image_ref:
        required: true
        type: string
      docker_image_digest:
        required: true
        type: string
      is_docker_image:
        required: true
        type: boolean
    secrets:
      PAT:
        required: true

jobs:
  sign-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set digest
        id: digest
        run: |
          if [[ "${{ inputs.is_docker_image }}" == "true" ]]; then
            echo "Using provided image digest: ${{ inputs.docker_image_digest }}"
            echo "digest=${{ inputs.docker_image_digest }}" >> "$GITHUB_OUTPUT"
          else
            echo "ERROR: Non-Docker image signing not implemented"
            exit 1
          fi
