name: Build and Call Signing Workflow with Auto-detect

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.get_digest.outputs.digest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "FROM alpine" > Dockerfile
          echo "RUN echo Hello world > /hello.txt" >> Dockerfile
          docker build -t ghcr.io/marcdonovan/sigstore/test-image:latest .

      - name: Login to GHCR
        env:
          PAT_TOKEN: ${{ secrets.PAT }}
        run: echo "$PAT_TOKEN" | docker login ghcr.io -u marcdonovan --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/marcdonovan/sigstore/test-image:latest

      - name: Get Docker image digest
        id: get_digest
        run: |
          FULL_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/marcdonovan/sigstore/test-image:latest)
          echo "Full digest: $FULL_DIGEST"
          echo "digest=${FULL_DIGEST#*@}" >> "$GITHUB_OUTPUT"

  call-sign-artifact:
    needs: build
    uses: marcdonovan/sigstore/.github/workflows/sign-and-verify.yaml@main
    with:
      docker_image_ref: ghcr.io/marcdonovan/sigstore/test-image:latest
      docker_image_digest: ${{ needs.build.outputs.image_digest }}
    secrets:
      PAT: ${{ secrets.PAT }}
    permissions:
      id-token: write
      contents: read
