name: Sign and Verify Artifact

on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        type: string
      artifact_path:
        required: false
        type: string
      docker_image_ref:
        required: false
        type: string
      docker_image_digest:
        required: false
        type: string
    secrets:
      PAT:
        required: true

jobs:
  sign-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Detect and Sign
        run: |
          echo "docker_image_ref=${{ inputs.docker_image_ref }}"
          echo "docker_image_digest=${{ inputs.docker_image_digest }}"
          echo "artifact_path=${{ inputs.artifact_path }}"
          
          if [[ -n "${{ inputs.docker_image_ref }}" && -n "${{ inputs.docker_image_digest }}" ]]; then
            echo "Signing Docker image..."
            echo "Digest: ${{ inputs.docker_image_digest }}"
            # Sign Docker image logic here

          elif [[ -n "${{ inputs.artifact_path }}" ]]; then
            echo "Signing binary artifact..."
            # Example: digest=$(oras push ...)
            # echo "digest=$digest" >> "$GITHUB_OUTPUT"
          else
            echo "ERROR: No artifact to sign. Please provide either docker_image_ref + digest OR artifact_path."
            exit 1
          fi
