name: Build, Sign, and Attest with Provenance

on:
  workflow_dispatch:

jobs:
  build-sign-attest:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Required for keyless signing

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build binary artifact
        run: |
          echo "Hello world" > myapp.txt
          tar -czf myapp.tar.gz myapp.txt

      - name: Install Cosign v2.2.0
        run: |
          curl -Lo cosign https://github.com/sigstore/cosign/releases/download/v2.2.0/cosign-linux-amd64
          chmod +x cosign
          sudo mv cosign /usr/local/bin/cosign

      - name: Install ORAS CLI
        run: |
          curl -sLo oras.zip https://github.com/oras-project/oras/releases/download/v0.18.0/oras_0.18.0_linux_amd64.zip
          unzip oras.zip oras
          chmod +x oras
          sudo mv oras /usr/local/bin/oras

      - name: Verify ORAS install
        run: oras version

      - name: Push artifact to GHCR
        run: |
          IMAGE="ghcr.io/${{ github.repository }}/myapp:latest"
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin
          oras push "$IMAGE" \
            --manifest-config /dev/null:application/vnd.oci.image.config.v1+json \
            myapp.tar.gz:application/gzip
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Sign artifact with Cosign
        run: |
          cosign sign --yes "$IMAGE"

      - name: Generate provenance.json
        run: |
          DIGEST=$(sha256sum myapp.tar.gz | cut -d ' ' -f1)
          cat <<EOF > provenance.json
          {
            "_type": "https://in-toto.io/Statement/v0.1",
            "subject": [{
              "name": "myapp.tar.gz",
              "digest": {
                "sha256": "$DIGEST"
              }
            }],
            "predicateType": "https://slsa.dev/provenance/v0.2",
            "predicate": {
              "builder": {
                "id": "https://github.com/${{ github.repository }}/.github/workflows/${{ github.workflow }}"
              },
              "buildType": "github-actions",
              "invocation": {
                "configSource": {
                  "uri": "git+https://github.com/${{ github.repository }}",
                  "digest": {
                    "sha1": "${{ github.sha }}"
                  },
                  "entryPoint": "${{ github.workflow }}"
                },
                "parameters": {},
                "environment":
