name: Build, Sign, Attest Binary

on:
  workflow_dispatch:

jobs:
  build-sign-attest:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for Sigstore keyless signing
      contents: read    # Required to read from repo (e.g., during checkout)
      packages: write   # Required to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binary artifact
        run: |
          echo "Hello world" > myapp.txt
          tar -czf myapp.tar.gz myapp.txt

      - name: Install Cosign v2.2.0
        run: |
          COSIGN_VERSION=v2.2.0
          mkdir -p $HOME/.local/bin
          curl -Lo $HOME/.local/bin/cosign https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64
          chmod +x $HOME/.local/bin/cosign

      - name: Add cosign to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check cosign version and path
        run: |
          which cosign
          cosign version

      - name: Upload artifact to OCI registry
        run: |
          REPO="ghcr.io/${{ github.repository }}/myapp"
          TAG="latest"
          cosign upload blob --repo $REPO --tag $TAG myapp.tar.gz
          echo "IMAGE=$REPO:$TAG" >> $GITHUB_ENV

      - name: Sign artifact with Cosign (keyless)
        run: |
          cosign sign --yes $IMAGE

      - name: Create predicate file
        run: |
          cat <<EOF > predicate.json
          {
            "builder": "${{ github.actor }}",
            "buildType": "github-actions",
            "commit": "${{ github.sha }}"
          }
          EOF

      - name: Generate and upload attestation (keyless)
        run: |
          cosign attest --yes \
            --type custom \
            --predicate predicate.json \
            $IMAGE
